# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/ui/default.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(600, 400)
        MainWindow.setMinimumSize(QtCore.QSize(0, 400))
        MainWindow.setMaximumSize(QtCore.QSize(600, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalToolBox = QtWidgets.QToolBox(self.centralwidget)
        self.verticalToolBox.setGeometry(QtCore.QRect(20, 60, 221, 181))
        self.verticalToolBox.setObjectName("verticalToolBox")
        self.verticalToolBoxPage1 = QtWidgets.QWidget()
        self.verticalToolBoxPage1.setGeometry(QtCore.QRect(0, 0, 221, 115))
        self.verticalToolBoxPage1.setObjectName("verticalToolBoxPage1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalToolBoxPage1)
        self.verticalLayout.setContentsMargins(1, 1, -1, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_nuser = QtWidgets.QPushButton(self.verticalToolBoxPage1)
        self.btn_nuser.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_nuser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_nuser.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_nuser.setObjectName("btn_nuser")
        self.verticalLayout.addWidget(self.btn_nuser)
        self.pushButton = QtWidgets.QPushButton(self.verticalToolBoxPage1)
        self.pushButton.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.verticalToolBox.addItem(self.verticalToolBoxPage1, "")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 221, 115))
        self.page.setObjectName("page")
        self.btn_exam = QtWidgets.QPushButton(self.page)
        self.btn_exam.setGeometry(QtCore.QRect(10, 0, 200, 50))
        self.btn_exam.setMinimumSize(QtCore.QSize(200, 50))
        self.btn_exam.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_exam.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_exam.setObjectName("btn_exam")
        self.btn_consult = QtWidgets.QPushButton(self.page)
        self.btn_consult.setGeometry(QtCore.QRect(10, 50, 200, 50))
        self.btn_consult.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_consult.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_consult.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_consult.setAutoFillBackground(False)
        self.btn_consult.setCheckable(False)
        self.btn_consult.setAutoRepeat(False)
        self.btn_consult.setAutoDefault(False)
        self.btn_consult.setDefault(False)
        self.btn_consult.setFlat(False)
        self.btn_consult.setObjectName("btn_consult")
        self.verticalToolBox.addItem(self.page, "")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 320, 151, 31))
        self.label_2.setStyleSheet("font: 8pt \"Cantarell\";")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 70, 271, 161))
        self.label.setStyleSheet("font: 75 11pt \"Cantarell\";\n"
"color: #0090FF")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 24))
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuSobre = QtWidgets.QMenu(self.menubar)
        self.menuSobre.setObjectName("menuSobre")
        self.menuDebug = QtWidgets.QMenu(self.menubar)
        self.menuDebug.setObjectName("menuDebug")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNovo_Usu_rio = QtWidgets.QAction(MainWindow)
        self.actionNovo_Usu_rio.setObjectName("actionNovo_Usu_rio")
        self.actionConsultar = QtWidgets.QAction(MainWindow)
        self.actionConsultar.setObjectName("actionConsultar")
        self.actionFechar = QtWidgets.QAction(MainWindow)
        self.actionFechar.setObjectName("actionFechar")
        self.actionLicen_a = QtWidgets.QAction(MainWindow)
        self.actionLicen_a.setObjectName("actionLicen_a")
        self.actionDesenvolvedor = QtWidgets.QAction(MainWindow)
        self.actionDesenvolvedor.setObjectName("actionDesenvolvedor")
        self.actionDesenvolvedor_2 = QtWidgets.QAction(MainWindow)
        self.actionDesenvolvedor_2.setObjectName("actionDesenvolvedor_2")
        self.actionPorta_Serial = QtWidgets.QAction(MainWindow)
        self.actionPorta_Serial.setObjectName("actionPorta_Serial")
        self.actionGerenciar_Usu_rio = QtWidgets.QAction(MainWindow)
        self.actionGerenciar_Usu_rio.setObjectName("actionGerenciar_Usu_rio")
        self.actionGerenciar_Exames = QtWidgets.QAction(MainWindow)
        self.actionGerenciar_Exames.setObjectName("actionGerenciar_Exames")
        self.menuArquivo.addAction(self.actionNovo_Usu_rio)
        self.menuArquivo.addAction(self.actionGerenciar_Usu_rio)
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.actionConsultar)
        self.menuArquivo.addAction(self.actionGerenciar_Exames)
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.actionFechar)
        self.menuSobre.addAction(self.actionLicen_a)
        self.menuSobre.addAction(self.actionDesenvolvedor)
        self.menuSobre.addAction(self.actionDesenvolvedor_2)
        self.menuDebug.addAction(self.actionPorta_Serial)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuSobre.menuAction())
        self.menubar.addAction(self.menuDebug.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Urofluxometria"))
        self.btn_nuser.setText(_translate("MainWindow", "Novo Usuário"))
        self.pushButton.setText(_translate("MainWindow", "Gerenciar Usuários"))
        self.verticalToolBox.setItemText(self.verticalToolBox.indexOf(self.verticalToolBoxPage1), _translate("MainWindow", "Usuário"))
        self.btn_exam.setText(_translate("MainWindow", "Relizar Exame"))
        self.btn_consult.setText(_translate("MainWindow", "Gerenciar Exames"))
        self.verticalToolBox.setItemText(self.verticalToolBox.indexOf(self.page), _translate("MainWindow", "Exame"))
        self.label_2.setText(_translate("MainWindow", "Exame Fluxometria 2018\n"
"Universidade Federal do Pará"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:72pt; font-weight:600;\">Pymic</span></p><p align=\"right\"><span style=\" font-size:14pt; font-weight:600;\">open source</span></p></body></html>"))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo"))
        self.menuSobre.setTitle(_translate("MainWindow", "Sobre"))
        self.menuDebug.setTitle(_translate("MainWindow", "Debug"))
        self.actionNovo_Usu_rio.setText(_translate("MainWindow", "Novo Usuário"))
        self.actionConsultar.setText(_translate("MainWindow", "Realizar Exame"))
        self.actionFechar.setText(_translate("MainWindow", "Fechar"))
        self.actionLicen_a.setText(_translate("MainWindow", "Licença"))
        self.actionDesenvolvedor.setText(_translate("MainWindow", "Software"))
        self.actionDesenvolvedor_2.setText(_translate("MainWindow", "Desenvolvedor"))
        self.actionPorta_Serial.setText(_translate("MainWindow", "Porta Serial"))
        self.actionPorta_Serial.setShortcut(_translate("MainWindow", "Alt+S"))
        self.actionGerenciar_Usu_rio.setText(_translate("MainWindow", "Gerenciar Usuários"))
        self.actionGerenciar_Exames.setText(_translate("MainWindow", "Gerenciar Exames"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

