# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/ui/examDetail.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_examDetail(object):
    def setupUi(self, examDetail):
        examDetail.setObjectName("examDetail")
        examDetail.resize(992, 652)
        examDetail.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(examDetail)
        self.centralwidget.setObjectName("centralwidget")
        self.mpl_widget = QtWidgets.QWidget(self.centralwidget)
        self.mpl_widget.setGeometry(QtCore.QRect(0, 80, 992, 551))
        self.mpl_widget.setMinimumSize(QtCore.QSize(970, 540))
        self.mpl_widget.setStyleSheet("background-color: #000;")
        self.mpl_widget.setObjectName("mpl_widget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 3, 971, 74))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        self.label_7.setMaximumSize(QtCore.QSize(191, 22))
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setMaximumSize(QtCore.QSize(190, 22))
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(190, 22))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setMaximumSize(QtCore.QSize(190, 22))
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_cpf = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_cpf.setStyleSheet("")
        self.label_cpf.setText("")
        self.label_cpf.setObjectName("label_cpf")
        self.gridLayout.addWidget(self.label_cpf, 3, 1, 1, 1)
        self.label_genr = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_genr.setStyleSheet("")
        self.label_genr.setText("")
        self.label_genr.setObjectName("label_genr")
        self.gridLayout.addWidget(self.label_genr, 3, 3, 1, 1)
        self.label_date = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_date.setStyleSheet("")
        self.label_date.setText("")
        self.label_date.setObjectName("label_date")
        self.gridLayout.addWidget(self.label_date, 3, 5, 1, 1)
        self.label_name = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_name.setStyleSheet("")
        self.label_name.setText("")
        self.label_name.setObjectName("label_name")
        self.gridLayout.addWidget(self.label_name, 0, 1, 1, 6)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_data_qmax = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_data_qmax.setText("")
        self.label_data_qmax.setObjectName("label_data_qmax")
        self.gridLayout.addWidget(self.label_data_qmax, 4, 1, 1, 1)
        self.label_data_qmean = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_data_qmean.setText("")
        self.label_data_qmean.setObjectName("label_data_qmean")
        self.gridLayout.addWidget(self.label_data_qmean, 4, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 2, 1, 1)
        self.label_data_tqmax = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_data_tqmax.setText("")
        self.label_data_tqmax.setObjectName("label_data_tqmax")
        self.gridLayout.addWidget(self.label_data_tqmax, 4, 3, 1, 1)
        examDetail.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(examDetail)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 992, 24))
        self.menubar.setObjectName("menubar")
        examDetail.setMenuBar(self.menubar)

        self.retranslateUi(examDetail)
        QtCore.QMetaObject.connectSlotsByName(examDetail)

    def retranslateUi(self, examDetail):
        _translate = QtCore.QCoreApplication.translate
        examDetail.setWindowTitle(_translate("examDetail", "Detalhes do Exame"))
        self.label_7.setText(_translate("examDetail", "<html><head/><body><p><span style=\" font-weight:600; color:#55aa00;\">Data do Exame</span></p></body></html>"))
        self.label_5.setText(_translate("examDetail", "<html><head/><body><p><span style=\" font-weight:600; color:#55aa00;\">Gênero</span></p></body></html>"))
        self.label.setText(_translate("examDetail", "<html><head/><body><p><span style=\" font-weight:600; color:#55aa00;\">Nome Paciente:</span></p></body></html>"))
        self.label_3.setText(_translate("examDetail", "<html><head/><body><p><span style=\" font-weight:600; color:#55aa00;\">CPF</span></p></body></html>"))
        self.label_4.setText(_translate("examDetail", "QMáx"))
        self.label_2.setText(_translate("examDetail", "QMédio"))
        self.label_6.setText(_translate("examDetail", "TQMáx"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    examDetail = QtWidgets.QMainWindow()
    ui = Ui_examDetail()
    ui.setupUi(examDetail)
    examDetail.show()
    sys.exit(app.exec_())

